#!/usr/bin/env python3

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# Columns generated by the PM Sampling collector that are not metrics.
METADATA_COLUMNS = {
    "sample",
    "start_ns",
    "end_ns",
    "duration_ns",
}


def safe_filename(name: str) -> str:
    """
    Convert a CUPTI metric name into a safe filename.
    """
    name = re.sub(r"[^a-zA-Z0-9._-]", "_", name)
    return name[:200]


def detect_metrics(df: pd.DataFrame) -> list[str]:
    """
    Automatically detect PM Sampling metric columns.
    """
    return [
        column
        for column in df.columns
        if column not in METADATA_COLUMNS
        and column != "time_ms"
    ]


def get_ylabel(metric: str) -> str:
    """
    Infer a useful Y-axis label from the CUPTI metric name.

    This is only for visualization. It does not modify the data.
    """
    if "pct_of_peak_sustained_elapsed" in metric:
        return "Percent of peak sustained elapsed (%)"

    if ".per_second" in metric:
        return "Rate (per second)"

    return "Metric value"


def plot_metric(
    df: pd.DataFrame,
    metric: str,
    output_dir: Path,
) -> None:
    """
    Generate and save one plot for one PM Sampling metric.
    """

    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(
        df["time_ms"],
        df[metric],
        linewidth=1.2,
    )

    ax.set_title(metric)
    ax.set_xlabel("Time since first valid sample (ms)")
    ax.set_ylabel(get_ylabel(metric))

    ax.grid(
        True,
        linestyle="--",
        alpha=0.4,
    )

    # Percentage metrics have a natural 0-100 % scale.
    if "pct_of_peak_sustained_elapsed" in metric:
        ax.set_ylim(0, 100)

    fig.tight_layout()

    output_file = output_dir / f"{safe_filename(metric)}.png"

    fig.savefig(
        output_file,
        dpi=150,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(f"[OK] {output_file}")


def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Generate plots from a CSV produced by the "
            "CUPTI PM Sampling collector."
        )
    )

    parser.add_argument(
        "csv_file",
        type=Path,
        help="PM Sampling CSV file",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path("plots"),
        help="Output directory (default: plots)",
    )

    parser.add_argument(
        "--keep-first-sample",
        action="store_true",
        help=(
            "Do not discard sample 0. By default sample 0 is "
            "discarded because its timestamp interval may be anomalous."
        ),
    )

    args = parser.parse_args()

    # ---------------------------------------------------------
    # Validate input
    # ---------------------------------------------------------

    if not args.csv_file.exists():
        raise SystemExit(
            f"Error: CSV file not found: {args.csv_file}"
        )

    # ---------------------------------------------------------
    # Load CSV
    # ---------------------------------------------------------

    df = pd.read_csv(args.csv_file)

    if df.empty:
        raise SystemExit("Error: CSV contains no samples.")

    print(f"Input: {args.csv_file}")
    print(f"Samples in CSV: {len(df)}")

    # ---------------------------------------------------------
    # Validate metadata
    # ---------------------------------------------------------

    required_columns = {
        "sample",
        "start_ns",
        "end_ns",
        "duration_ns",
    }

    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise SystemExit(
            "Error: missing required columns: "
            + ", ".join(sorted(missing_columns))
        )

    # ---------------------------------------------------------
    # Remove first sample
    #
    # We observed on Thor that sample 0 can contain an anomalous
    # timestamp interval. The raw CSV is kept untouched; the
    # sample is excluded only during offline analysis.
    # ---------------------------------------------------------

    if not args.keep_first_sample:

        if len(df) < 2:
            raise SystemExit(
                "Error: cannot discard sample 0 because "
                "the CSV contains only one sample."
            )

        print(
            f"Discarding sample 0 "
            f"(duration = {df.iloc[0]['duration_ns']} ns)"
        )

        df = df.iloc[1:].copy()

    # ---------------------------------------------------------
    # Sort samples chronologically
    # ---------------------------------------------------------

    df = df.sort_values("start_ns").reset_index(drop=True)

    # ---------------------------------------------------------
    # Build time axis using the REAL CUPTI timestamps.
    #
    # Do NOT calculate time using:
    #
    #     sample_index * requested_sampling_interval
    #
    # because the actual PM Sampling interval can differ from
    # the requested interval.
    # ---------------------------------------------------------

    first_timestamp_ns = df["start_ns"].iloc[0]

    df["time_ms"] = (
        df["start_ns"] - first_timestamp_ns
    ) / 1_000_000.0

    # ---------------------------------------------------------
    # Detect metrics dynamically
    # ---------------------------------------------------------

    metrics = detect_metrics(df)

    if not metrics:
        raise SystemExit(
            "Error: no PM Sampling metric columns found."
        )

    print(f"Valid samples: {len(df)}")
    print(f"Metrics found: {len(metrics)}")

    for metric in metrics:
        print(f"  - {metric}")

    # ---------------------------------------------------------
    # Create output directory
    # ---------------------------------------------------------

    args.output.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(f"\nGenerating plots in: {args.output}/")

    # ---------------------------------------------------------
    # Generate one plot per metric
    # ---------------------------------------------------------

    for metric in metrics:

        # Convert metric to numeric just in case the CSV contains
        # an invalid/NaN value.
        df[metric] = pd.to_numeric(
            df[metric],
            errors="coerce",
        )

        if df[metric].notna().sum() == 0:
            print(
                f"[SKIP] {metric}: no valid numeric samples"
            )
            continue

        plot_metric(
            df=df,
            metric=metric,
            output_dir=args.output,
        )

    # ---------------------------------------------------------
    # Summary
    # ---------------------------------------------------------

    total_time_ms = (
        df["end_ns"].iloc[-1]
        - df["start_ns"].iloc[0]
    ) / 1_000_000.0

    mean_interval_ms = (
        df["duration_ns"].mean()
        / 1_000_000.0
    )

    print()
    print("PM Sampling summary")
    print("-------------------")
    print(f"Samples analysed : {len(df)}")
    print(f"Metrics          : {len(metrics)}")
    print(f"Total time       : {total_time_ms:.3f} ms")
    print(f"Mean sample time : {mean_interval_ms:.3f} ms")
    print(f"Output directory : {args.output}")


if __name__ == "__main__":
    main()

# example python plot_pm_sampling.py results/pm_sampling.csv --output plots